### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ezrec** [healeycodes/noter#4]
I'm interested in contributing an adaptation of your editor, to make it a library that can be more easily pulled into another Ebitengine application.

Can you add a license to this code, so that it's clearer in how it can be used?

I prefer MIT and BSD-3 Clause myself, as Go is a statically linked language that doesn't play well with mixing in GPL libraries, but of course it's up to you.

**Comment by healeycodes** [comment]
Sounds awesome @ezrec, good luck with it. I've added an MIT license.
